CREATE TABLE public.t_cpgram_grievance (
    id varchar NOT NULL,
    description varchar NULL,
    raised_by varchar NULL,
    mobile_no varchar NULL,
    dept_name varchar NULL,
    dept_code varchar NULL,
    gro_name varchar NULL,
    status varchar NULL,
    field_1 varchar NULL,
    field_2 varchar NULL,
    field_3 varchar NULL,
    field_4 varchar NULL,
    field_5 varchar NULL,
    grievance_id varchar NULL,
    free_text_1 varchar NULL,
    free_text_2 varchar NULL,
    tracking_link varchar NULL,
    created_by varchar NULL,
    created_on date NULL,
    last_updated_by varchar NULL,
    last_updated_on date NULL,
    CONSTRAINT t_cpgram_grievance_pk PRIMARY KEY (id)
);
