-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL
CREATE SEQUENCE m_demo_cpgram_categories_code_id_seq
  START WITH 1
  INCREMENT BY 1;

CREATE TABLE m_demo_cpgram_categories (
    id varchar NOT NULL PRIMARY KEY,
    description varchar NULL,
    orgcode varchar NULL,
    parent varchar NULL,
    stage numeric NULL,
    descriptionhindi text NULL,
    monitoringcode numeric NULL,
    mappingcode varchar NULL,
    fieldcode numeric NULL,
    destination varchar NULL,
    isactive varchar NULL,
    embedding public.vector NULL,
    field_details varchar NULL,
    code int2 NOT NULL
);
-- Create the sequence for the code column (if it doesn't already exist)
CREATE SEQUENCE IF NOT EXISTS m_demo_cpgram_categories_code_id_seq
  START WITH 1
  INCREMENT BY 1;

-- Alter the code column to use the sequence for auto-increment
ALTER TABLE m_demo_cpgram_categories
  ALTER COLUMN code SET DEFAULT nextval('m_demo_cpgram_categories_code_id_seq'::regclass);

